# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];

  hardware.enableRedistributableFirmware = true;

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.rtl8852au ];
  boot.kernelPackages = pkgs.linuxPackages_6_12;

  # Add the udev rule to trigger usb_modeswitch for the storage mode ID
  services.udev.extraRules = ''
    ATTR{idVendor}=="0bda", ATTR{idProduct}=="1a2b", RUN+="${
      lib.getExe pkgs.usb-modeswitch
    } -K -v 0bda -p 1a2b"
  '';

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-label/DataDrive"; # This is your /dev/sda1
    fsType = "ext4";
  };

  fileSystems."/home/joel/Code" = {
    device = "/dev/disk/by-uuid/55f85a49-7faa-44e0-b416-6eac820faadc";
    fsType = "ext4";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/34197c02-19aa-4176-83ba-652edf72b1a0";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FDB7-5CF1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  hardware.graphics.extraPackages = [ pkgs.libvdpau-va-gl ];

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3ff00db8-aef8-440a-9430-ac688887e0a4"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.

  networking = {
    networkmanager.enable = true;
    useDHCP = lib.mkDefault true;
    firewall.allowedTCPPorts = [ 57621 ];
    firewall.allowedUDPPorts = [ 5353 ];
    firewall.trustedInterfaces = [ "virbr1" ];
  };
  # networking.useDHCP = lib.mkDefault true;
  # networking.nameservers =
  #   [ "8.8.8.8" "8.8.4.4" ]; # Google's public DNS servers
  # #

  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u7.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
